#!/bin/bash
# Download desktop-config-lite cookbook from remote and extract contents.
download_cookbook() {
  local url="https://supermarket.chef.io/cookbooks/desktop-config-lite/download"

  # Resolve redirects and download from URL
  local finalurl=$(curl --silent --location --head --output /dev/null --write-out '%{url_effective}' -- "$url")
  curl --silent $finalurl -o desktop-config-lite.tgz
  # Extract contents
  tar -xvzf ./desktop-config-lite.tgz
  rm ./desktop-config-lite.tgz
}

setup_cookbook() {
  cd ~/.chef/cookbooks/desktop-config-lite
  cat <<-EOF > Policyfile.rb
name 'desktop-config-lite'
run_list 'desktop-config-lite::default'
cookbook 'desktop-config-lite', path: '.'
EOF
  cat <<-EOF > recipes/default.rb
include_recipe 'desktop-config-lite::macos' if macos?
include_recipe 'desktop-config-lite::windows' if windows?
EOF
  chef install Policyfile.rb
}

echo "Setting up cookbook in local"
cd ~/.chef/cookbooks
download_cookbook && setup_cookbook