#!/bin/bash
# Download desktop-config-lite cookbook from remote and extract contents.
download_cookbook() {
  local url="https://supermarket.chef.io/cookbooks/desktop-config-lite/download"

  # Resolve redirects and download from URL
  local finalurl=$(curl --silent --location --head --output /dev/null --write-out '%{url_effective}' -- "$url")
  curl --silent $finalurl -o desktop-config-lite.tgz
  # Extract contents
  tar -xvzf ./desktop-config-lite.tgz
  rm ./desktop-config-lite.tgz
}

cd ~/.chef/cookbooks && download_cookbook
